import React from 'react';
import { ArrowLeft, Sparkles, Swords, Shield, Zap, Activity, Heart, Timer } from 'lucide-react';
import { TYPES, RARITIES, ABILITIES } from '../data/gameData';

export default function PetDetailScreen({ pet, onBack }) {
    const typeInfo = TYPES[pet.type];
    const rarityInfo = RARITIES[pet.rarity];
    const ability = ABILITIES[pet.abilityId];
    const abilityTypeInfo = TYPES[ability.element] || { color: 'text-slate-400', label: 'Neutral' };
    return (
      <div className="pt-2 pb-10 space-y-6 animate-in slide-in-from-right duration-300">
        <div className="flex items-center gap-2"><button onClick={onBack} className="p-2 bg-slate-800 rounded-full hover:bg-slate-700 transition-colors"><ArrowLeft className="w-5 h-5" /></button><h2 className="text-xl font-bold">Pet Details</h2></div>
        <div className={`rounded-3xl p-0.5 bg-gradient-to-br ${rarityInfo.bg} to-slate-800`}><div className="bg-slate-900 rounded-[22px] p-5 relative overflow-hidden"><div className="flex justify-between items-start mb-6 relative z-10"><div><div className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase border ${rarityInfo.border} ${rarityInfo.color} mb-1 bg-slate-800/80`}><Sparkles className="w-3 h-3" /> {rarityInfo.label}</div><h3 className="text-3xl font-black">{pet.name}</h3><div className={`text-sm font-bold ${typeInfo.color} flex items-center gap-1`}><div className="w-4 h-4">{typeInfo.icon}</div> {typeInfo.label}-Typ</div></div><div className={`w-20 h-20 ${typeInfo.bg} rounded-2xl flex items-center justify-center text-4xl shadow-lg`}>{typeInfo.icon}</div></div>
        <div className="bg-slate-800/50 p-4 rounded-xl border border-white/5 mb-4 relative z-10"><div className="flex justify-between items-center mb-4"><h4 className="text-xs text-slate-500 font-bold uppercase">Stats (Lvl {pet.level})</h4><div className="text-[10px] text-slate-400">Wachstum: <span className="text-green-400">+{Math.round((0.05 * rarityInfo.multi)*100)}%</span> / Lvl</div></div><div className="grid grid-cols-2 gap-x-8 gap-y-2"><div className="flex justify-between items-center text-sm border-b border-white/5 pb-1"><span className="text-slate-400 flex items-center gap-2"><Swords className="w-4 h-4 text-red-400"/> Angriff</span><span className="font-bold">{pet.atk}</span></div><div className="flex justify-between items-center text-sm border-b border-white/5 pb-1"><span className="text-slate-400 flex items-center gap-2"><Shield className="w-4 h-4 text-slate-300"/> Rüstung</span><span className="font-bold">{pet.def}</span></div><div className="flex justify-between items-center text-sm border-b border-white/5 pb-1"><span className="text-slate-400 flex items-center gap-2"><Zap className="w-4 h-4 text-purple-400"/> Fähigkeit</span><span className="font-bold">{pet.ap}</span></div><div className="flex justify-between items-center text-sm border-b border-white/5 pb-1"><span className="text-slate-400 flex items-center gap-2"><Activity className="w-4 h-4 text-blue-300"/> Resistenz</span><span className="font-bold">{pet.res}</span></div><div className="flex justify-between items-center text-sm pt-1"><span className="text-slate-400 flex items-center gap-2"><Activity className="w-4 h-4 text-yellow-400"/> Speed</span><span className="font-bold">{pet.speed}</span></div><div className="flex justify-between items-center text-sm pt-1"><span className="text-slate-400 flex items-center gap-2"><Heart className="w-4 h-4 text-green-400"/> HP</span><span className="font-bold">{pet.hp}/{pet.maxHp}</span></div></div></div>
        <div className="bg-slate-800/50 p-3 rounded-xl border border-white/5 mb-4 relative z-10"><div className="flex justify-between text-[10px] mb-1 font-bold text-slate-400"><span>XP Fortschritt</span><span>{pet.xp} / {pet.maxXp}</span></div><div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden"><div className="h-full bg-yellow-400" style={{width: `${(pet.xp / pet.maxXp) * 100}%`}}></div></div></div>
        <div className="bg-indigo-900/20 border border-indigo-500/30 p-4 rounded-xl relative z-10"><div className="flex justify-between items-start mb-2"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded bg-indigo-500 flex items-center justify-center text-white"><Zap className="w-5 h-5 fill-current" /></div><div><div className="font-bold text-sm text-indigo-300">{ability.name}</div><div className="text-[10px] text-indigo-400/70 uppercase">Aktive Fähigkeit</div></div></div><div className="bg-slate-900 text-[10px] px-2 py-1 rounded border border-white/10 flex items-center gap-1 text-slate-400"><Timer className="w-3 h-3" /> {ability.cd} Runden</div></div><p className="text-xs text-slate-300 leading-relaxed mb-2">{ability.desc}</p><div className="flex items-center gap-1 text-[10px] font-bold uppercase">Element: <span className={`${abilityTypeInfo.color}`}>{abilityTypeInfo.label}</span></div></div>
        <div className={`absolute -top-10 -right-10 w-64 h-64 ${typeInfo.bg} opacity-10 blur-3xl rounded-full pointer-events-none`}></div></div></div></div>
    );
}