import React from 'react';
import { ArrowLeft, LayoutGrid, Backpack, ThermometerSun, Heart } from 'lucide-react';

export default function PetHub({ onBack, onInventory, onBreed, onHatchery, onItemInventory }) {
  return (
    <div className="space-y-4 pt-4 animate-in fade-in slide-in-from-right duration-300">
      <div className="flex items-center gap-2 mb-2"><button onClick={onBack} className="p-2 bg-slate-800 rounded-full hover:bg-slate-700"><ArrowLeft className="w-5 h-5" /></button><h2 className="text-2xl font-black italic text-emerald-400">PET HUB</h2></div>
      <button onClick={onInventory} className="w-full bg-slate-800 border border-slate-700 p-5 rounded-3xl flex items-center justify-between hover:bg-slate-750 active:scale-95 transition-all group"><div className="flex items-center gap-4"><div className="w-12 h-12 bg-blue-500/20 text-blue-400 rounded-2xl flex items-center justify-center group-hover:bg-blue-500 group-hover:text-white transition-colors"><LayoutGrid className="w-6 h-6" /></div><div className="text-left"><div className="font-bold text-lg">Pet Sammlung</div><div className="text-xs text-slate-400">Alle deine Monster</div></div></div></button>
      <button onClick={onItemInventory} className="w-full bg-slate-800 border border-slate-700 p-5 rounded-3xl flex items-center justify-between hover:bg-slate-750 active:scale-95 transition-all group"><div className="flex items-center gap-4"><div className="w-12 h-12 bg-amber-500/20 text-amber-400 rounded-2xl flex items-center justify-center group-hover:bg-amber-500 group-hover:text-white transition-colors"><Backpack className="w-6 h-6" /></div><div className="text-left"><div className="font-bold text-lg">Item Inventar</div><div className="text-xs text-slate-400">Eier & Items</div></div></div></button>
      <button onClick={onHatchery} className="w-full bg-slate-800 border border-slate-700 p-5 rounded-3xl flex items-center justify-between hover:bg-slate-750 active:scale-95 transition-all group"><div className="flex items-center gap-4"><div className="w-12 h-12 bg-emerald-500/20 text-emerald-400 rounded-2xl flex items-center justify-center group-hover:bg-emerald-500 group-hover:text-white transition-colors"><ThermometerSun className="w-6 h-6" /></div><div className="text-left"><div className="font-bold text-lg">Brutstätte</div><div className="text-xs text-slate-400">Eier ausbrüten</div></div></div></button>
      <button onClick={onBreed} className="w-full bg-slate-800 border border-slate-700 p-5 rounded-3xl flex items-center justify-between hover:bg-slate-750 active:scale-95 transition-all group"><div className="flex items-center gap-4"><div className="w-12 h-12 bg-pink-500/20 text-pink-400 rounded-2xl flex items-center justify-center group-hover:bg-pink-500 group-hover:text-white transition-colors"><Heart className="w-6 h-6 fill-current" /></div><div className="text-left"><div className="font-bold text-lg">Zucht Labor</div><div className="text-xs text-slate-400">Neue Arten erschaffen</div></div></div></button>
    </div>
  );
}